In [20]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [21]:
df.head(3)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138

In [22]:
df.rename(columns={"entity" : "Pais"}, inplace=True)
df.rename(columns={"code" : "Code"}, inplace=True)
df.rename(columns={"code" : "Code"}, inplace=True)
df.rename(columns={"year" : "Anos"}, inplace=True)
df.rename(columns={"esperanza_de_vida" : "Esperanza_de_vida"}, inplace=True)

In [37]:
df.head(3)

            Code  Anos  life_expectancy_0
Pais
Afghanistan  AFG  1950            28.1563
Afghanistan  AFG  1951            28.5836
Afghanistan  AFG  1952            29.0138

In [33]:
print(df.columns.tolist())

['Code', 'Anos', 'life_expectancy_0']

In [38]:
#df.set_index("Pais", inplace=True)
df.reset_index(inplace=True)

In [39]:
df.loc[df["Pais"].str.contains("U", case=False, regex=True)]

                    Pais Code  Anos  life_expectancy_0
604             Anguilla  AIA  1950            55.0563
605             Anguilla  AIA  1951            55.5932
606             Anguilla  AIA  1952            56.0813
607             Anguilla  AIA  1953            56.5817
608             Anguilla  AIA  1954            57.0804
...                  ...  ...   ...                ...
21183  Wallis and Futuna  WLF  2019            77.9936
21184  Wallis and Futuna  WLF  2020            78.1637
21185  Wallis and Futuna  WLF  2021            77.4609
21186  Wallis and Futuna  WLF  2022            78.5005
21187  Wallis and Futuna  WLF  2023            78.6286

[7375 rows x 4 columns]

In [41]:
df.dropna(subset=["Code"], inplace=True)
df.isnull().sum()

Pais                 0
Code                 0
Anos                 0
life_expectancy_0    0
dtype: int64

In [ ]:
resultado = (
    df.groupby("Pais")["life_expectancy_0"]
      .mean()#Calcula el promedio de esperanza de vida para cada país.
      .sort_values(ascending=True)# Ordena los resultados de menor a mayor.
)
print(resultado)

Pais
USSR             32.700000
South Sudan      37.841631
Sierra Leone     43.189605
Mali             43.760793
Niger            44.187513
                   ...
Liechtenstein    76.288354
Guernsey         76.995827
Andorra          77.991046
San Marino       77.997265
Monaco           78.048231
Name: life_expectancy_0, Length: 247, dtype: float64

In [ ]:
#memoria_md = df.memory_usage()